
before_script:
- echo Setup here
- echo FOO=$FOO BAR=$BAR

install:
- echo Installing..
- echo FOO=$FOO BAR=$BAR

script:
- echo OK, lets start
- echo FOO=$FOO BAR=$BAR

after_script:
- echo Done, wrap it up

env:
- FOO=bar
- FOO=el BAR=baz
