
sudo: false

#
# Travis compatible build file for jenkins travis-yml
#

before_install:
- echo before install 1
- echo before install 2

install:
- echo Installing..
- echo "FOO=$FOO BAR=$BAR"

before_script:
- echo Setup here
- echo "FOO=$FOO BAR=$BAR"

script:
- echo OK, running build
- echo "FOO=$FOO BAR=$BAR"

after_script:
- echo Done, wrap it up

after_failure:
- echo Oh-oh

after_success:
- echo Yeah

# travis-yml does not support matrix builds?
env:
- FOO=el BAR=baz

